### ISSUE TITLE
Faith Response breakdown

### ISSUE THREAD

**Issue by justinmiller24** [gmo/arc#10]
Background:
- During the 60 Day Test, we saw a jump in the % of users that sent in the “No Decision - Needs Gospel Presentation” faith response. Justin would like to see a breakdown by source/domain of New Contacts that have the "No Decision" faith response, from June 2016 - September 2016. Mike thinks this can be accomplished by pulling the data from C2 or ARC by contact added in a given date range. This isn’t the same as form submissions, but it should be close enough.

Tasks:
- Write a query to pull New Contacts from ARC by contact added between 6/1/16 - 9/30/16, and provide a breakdown of source/domains and the # of contacts associated with each. Email the final results to Justin.

**Comment by mikegillis677** [comment]
https://docs.google.com/a/gmomail.org/spreadsheets/d/1Z1e-m_lQCxQOvWSblvs-SSF314FmPjv0kiKDuWqgGvQ/edit?usp=sharing
