### ISSUE TITLE
“Pool limit 100%” is not functioning intuitively

### ISSUE THREAD

**Issue by jason-gill** [gmo/arc#12]
Product Owner: Touhami

This issue was reported by Touhami and he says this is key functionality to response time.

Mike investigated this and said this:

_It appears that the “Pool limit 100%” is not functioning intuitively.  Instead of allowing people access to as many contacts as they want, it allows them access to as many contacts as are currently in the pool per day.  However, this means that as the pool dwindles, people who have already answered contacts can’t get anymore._

**Comment by mikegillis677** [comment]
Recommended solution:  Update the API code so that you can set the preference to "No limit" (i.e. remove the limit), and have them do that.  That's the way the system used to work before the last API rewrite
