### ISSUE TITLE
Turn off the Salesforce to Assist sync

### ISSUE THREAD

**Issue by jason-gill** [gmo/arc#17]
Reported By: Meg Bacino

Right now we sync between changes in Address and name both ways between Salesforce and Assist.  I would like to turn off the Salesforce to Assist sync and just change Salesforce if an OM updates their information in Assist.  We see too many issues going from Salesforce to Assist.  Especially when it comes to special characters.  They get transformed in Salesforce and then get fed back to Assist in "weird" form.  I can't correct them because now Assist has the "weird" characters.

**Comment by jason-gill** [comment]
Talked to Meg and we need to...
- [ ] turn off the Salesforce to Assist sync
- [ ] leave the Assist to Salesforce sync alone

**Comment by mikegillis677** [comment]
@jason-gill Changes are in branch feature/DEV-17-disable-salesforce-sync

**Comment by jason-gill** [comment]
@mikegillis677 Good to go.  Please push when convenient.
