### ISSUE TITLE
Reply Templates are concatenating name and state together

### ISSUE THREAD

**Issue by jason-gill** [gmo/arc#5]

**Comment by mikegillis677** [comment]
It appears that what is happening is that the first_name field is getting overwritten with the state name in some cases.  For example, see contact id 13266605 (Panama is state, overwrote the first_name field).

I do not see any evidence that this is happening all the time, it seems to be random.  Likely is happening on import, but I do not see anything obvious is the code.

**Comment by mikegillis677** [comment]
It looks like this was occurring due to some bad code in the "update" code path.  It happened 17% of the time because that is the number of contacts that go down the update path.
