### ISSUE TITLE
Weekly Discipleship Report - OTG checkboxes

### ISSUE THREAD

**Issue by justinmiller24** [gmo/arc#8]
Background:
- For OTG connections, GMO made the decision to count "total disciples with at least one checked connection checkbox" as part of the reported OTG number. For FY16, this accounted for 4,560 total seekers (disciples). For FY17, the overall goal will be 5,000 or 10,000, however a large number of these will come from the ARC discipleship dashboard checkboxes (de-duped), which Stacy / Becky do not currently have any visibility into.

Tasks:
- Generate the number of "total disciples with at least one checked connection checkbox" (all time number) on a weekly basis and send out to the same group that currently gets the automated (weekly) discipleship summary report. (Note: this can be included in the existing report, or sent separately, but the main idea is to give Stacy and others visibility into how this number progresses throughout the year.)

**Comment by mikegillis677** [comment]
It looks like the reports being generated show the new field being set to 0 in the summary.  This is incorrect.  However, I do not see any mistakes in the code that generates this, and I cannot reproduce in development (since in development I do not have the data sources that generates the report, given that it's heavily based on production configuration).

**Comment by justinmiller24** [comment]
@mikegillis677 can you copy/paste the query used to generate that data so me or someone else can take a look?

**Comment by mikegillis677** [comment]
I iterate the following query for each disciple id:
```
SELECT d.contact_id,
				COALESCE(lan.description, "Unknown") AS language,
				LOWER(ch.name) AS channel, c.first_name, c.last_name, dom.domain,
				`dec`.description AS faith_response, c.corr_in AS messages_in, c.messages_out,
				act.description AS form_action, plt.description AS platform,
				cty.description AS country, gen.description AS gender, age.description AS age,
				DATE(c.created_on) AS creation_date, d.first_contact, d.last_contact, d.expire_date,
				d.accept_christ, d.attend_church, d.attend_church_name, d.life_change,
				d.read_bible, d.pray_regularly, d.share_faith, d.connect_to_church,
				d.connect_to_church_name, d.connect_to_om, d.connect_to_om_name,
				d.connect_to_mission, d.connect_to_mission_name,
				LEAST(1, d.connect_to_church + d.connect_to_om + d.connect_to_mission) AS connect_to_any,
				d.adv_discipleship_materials,
				otg_connector.display_name AS partner_name, connector_languages.description AS partner_language,
				connector_countries.description AS partner_country,
				otg_handoff.confirmed_handoff AS is_confirmed_handoff,
				if(otg_handoff.confirmed_handoff IS NOT NULL, COALESCE(om_handoff_confirmation.is_connected, 0), NULL) AS confirmed_by_om,
				om_handoff_confirmation.updated_on AS confirmed_by_om_on,
				if(otg_handoff.confirmed_handoff IS NOT NULL, COALESCE(connector_handoff_confirmation.is_connected, 0), NULL) AS confirmed_by_partner,
				connector_handoff_confirmation.updated_on AS confirmed_by_partner_on
			FROM arc_disciples2 AS d
			LEFT JOIN arc_contacts AS c ON d.contact_id = c.id
			LEFT JOIN arc_contact_profile AS p ON d.contact_id = p.contact_id
			LEFT JOIN communication_channels AS ch ON c.comm_channel = ch.id
			LEFT JOIN arc_domains AS dom ON p.domain_id = dom.id
			LEFT JOIN arc_languages AS lan ON p.language_id = lan.id
			LEFT JOIN arc_answers AS `dec` ON p.faith_response_id = `dec`.id
			LEFT JOIN arc_answers AS act ON p.form_action_id = act.id
			LEFT JOIN arc_answers AS plt ON p.platform_id = plt.id
			LEFT JOIN arc_answers AS gen ON p.gender_id = gen.id
			LEFT JOIN arc_answers AS age ON p.age_id = age.id
			LEFT JOIN iso_3166 AS cty ON c.country = cty.id3 AND cty.id2 != "US"

			LEFT JOIN otg_handoff ON d.contact_id = otg_handoff.contact_id
			LEFT JOIN otg_handoff AS old_handoffs ON otg_handoff.contact_id = old_handoffs.contact_id
				AND otg_handoff.created_on < old_handoffs.created_on
			LEFT JOIN otg_connector ON otg_handoff.otg_connector_id = otg_connector.id
			LEFT JOIN arc_languages AS connector_languages ON otg_connector.language_id = connector_languages.id
			LEFT JOIN iso_3166 AS connector_countries ON otg_connector.country_id = connector_countries.id2
			LEFT JOIN otg_handoff_confirmation AS om_handoff_confirmation ON otg_handoff.id = om_handoff_confirmation.otg_handoff_id
				AND om_handoff_confirmation.confirmed_by = "om"
			LEFT JOIN otg_handoff_confirmation AS connector_handoff_confirmation ON otg_handoff.id = connector_handoff_confirmation.otg_handoff_id
				AND connector_handoff_confirmation.confirmed_by = "otg_connector"

			WHERE d.contact_id > ?
				AND d.expire_date > NOW()
				AND old_handoffs.id IS NULL
			ORDER BY contact_id ASC LIMIT 1000
```

The part of the query in question is `LEAST(1, d.connect_to_church + d.connect_to_om + d.connect_to_mission) AS connect_to_any,`

**Comment by justinmiller24** [comment]
@mikegillis677 The LEAST function looks correct, assuming that `d.connect_to_church`, `d.connect_to_om`, and `d.connect_to_mission` are all BOOLEANs or TINYINTs.

Here are some possible next steps:
1. Remove the LEAST statement and just do (d.connect_to_church + d.connect_to_om + d.connect_to_mission) AS connect_to_any to see if it's still 0 across the board. This will at least help narrow down if it's the LEAST statement.
2. Try running the SQL statement `SELECT LEAST(1, false + false + true)` to see if it's something with the DB or column schema
3. Limit to query to show only one row/disciple that you know has 2 or 3 of those checked, and see what you get

My guess is it's either failing in the SQL or in the application/iteration part
